/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
    kotlin("kapt") version "2.1.20"
}

dependencies {
    implementation(libs.io.javalin.javalin)
    implementation(libs.org.apache.commons.commons.email)
    implementation(libs.org.jetbrains.exposed.exposed.core)
    implementation(libs.org.jetbrains.kotlin.kotlin.stdlib)
    implementation(libs.com.github.kmehrunes.javalin.jwt)
    implementation(libs.io.javalin.community.openapi.javalin.openapi.plugin)
    implementation(libs.io.javalin.community.openapi.javalin.swagger.plugin)
    kapt(libs.io.javalin.community.openapi.annotation.processor)
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:2.1.20")
    testImplementation(libs.assertj)
    testImplementation(libs.org.jetbrains.exposed.exposed.jdbc)
    testImplementation(libs.com.zaxxer.hikaricp)
    testImplementation(libs.io.javalin.javalin.testtools)
    testImplementation(libs.com.github.kirviq.dumbster)
    testImplementation(libs.com.h2database.h2)
    testImplementation(libs.org.slf4j.slf4j.simple)
    implementation(kotlin("stdlib-jdk8"))
}

description = "app"
repositories {
    mavenCentral()
}

tasks.test {
    useJUnitPlatform()
}

kapt {
    java.targetCompatibility = JavaVersion.VERSION_21
    kotlin.jvmToolchain(21)
}