/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
    application
}

dependencies {
    implementation(project(":app"))
    implementation(project(":api"))
    implementation(libs.org.slf4j.slf4j.simple)
    implementation(libs.com.zaxxer.hikaricp)
    implementation(libs.io.github.cdimascio.dotenv.kotlin)
    implementation(libs.com.h2database.h2)
    implementation(libs.org.jetbrains.exposed.exposed.jdbc)
    implementation(libs.com.github.kirviq.dumbster)
    implementation(kotlin("stdlib-jdk8"))
}

description = "dev-env"
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}
application {
    mainClass = "io.github.costsplit.dev.backend.MainKt"
}