/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("org.openapi.generator") version "7.12.0"
    java
    `maven-publish`
}

sourceSets {
    main {
        java {
            srcDir(layout.buildDirectory.dir("generate-resources/main/src/main/java"))
        }
    }
}

openApiGenerate {
    inputSpec = "$projectDir/src/main/resources/openapi.json"
    generatorName = "java"
    apiPackage = "io.github.costsplit.api"
    invokerPackage = "io.github.costsplit.api.invoker"
    groupId = "io.github.costsplit"
    artifacts {
        id = "api"
    }
    modelPackage = "io.github.costsplit.api.model"
    library = "native"
    skipValidateSpec = true
}

description = "api"

val jacksonVersion = "2.17.1"
val jakartaAnnotationVersion = "1.3.5"
val beanValidationVersion = "2.0.2"
val junitVersion = "5.10.2"

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "io.github.costsplit"
            artifactId = "api"
            version = "0.1-SNAPSHOT"

            from(components["java"])
        }
    }
}

dependencies {
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("com.fasterxml.jackson.core:jackson-core:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion")
    implementation("org.openapitools:jackson-databind-nullable:0.2.1")
    implementation("jakarta.annotation:jakarta.annotation-api:$jakartaAnnotationVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
}

tasks.compileJava {
    dependsOn(tasks.openApiGenerate)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

